# Generated by Django 5.0.6 on 2024-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_schedule_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
